<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy-Array" data-toc-modified-id="Numpy-Array-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy Array</a></span><ul class="toc-item"><li><span><a href="#Listeden-Array-Yaratmak" data-toc-modified-id="Listeden-Array-Yaratmak-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Listeden Array Yaratmak</a></span></li><li><span><a href="#Array-Data-tipini-manuel-belirtmek" data-toc-modified-id="Array-Data-tipini-manuel-belirtmek-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Array Data tipini manuel belirtmek</a></span></li><li><span><a href="#Zero-Array" data-toc-modified-id="Zero-Array-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Zero Array</a></span><ul class="toc-item"><li><span><a href="#Multidimensional-Zero-Array" data-toc-modified-id="Multidimensional-Zero-Array-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Multidimensional Zero Array</a></span></li></ul></li><li><span><a href="#Spesific-element-array" data-toc-modified-id="Spesific-element-array-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Spesific element array</a></span><ul class="toc-item"><li><span><a href="#np.full()" data-toc-modified-id="np.full()-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>np.full()</a></span></li><li><span><a href="#HATIRLATMA" data-toc-modified-id="HATIRLATMA-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>HATIRLATMA</a></span></li></ul></li><li><span><a href="#Consequtive-Array's" data-toc-modified-id="Consequtive-Array's-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Consequtive Array's</a></span></li><li><span><a href="#Dividing-Interval" data-toc-modified-id="Dividing-Interval-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Dividing Interval</a></span></li><li><span><a href="#Normal-Distribution-Array" data-toc-modified-id="Normal-Distribution-Array-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Normal Distribution Array</a></span></li><li><span><a href="#Random-Integer-Array" data-toc-modified-id="Random-Integer-Array-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Random Integer Array</a></span></li><li><span><a href="#Identity-Matrix" data-toc-modified-id="Identity-Matrix-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Identity Matrix</a></span></li><li><span><a href="#Array-Operations" data-toc-modified-id="Array-Operations-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Array Operations</a></span></li><li><span><a href="#Array-Attributes" data-toc-modified-id="Array-Attributes-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>Array Attributes</a></span><ul class="toc-item"><li><span><a href="#.shape" data-toc-modified-id=".shape-1.11.1"><span class="toc-item-num">1.11.1&nbsp;&nbsp;</span>.shape</a></span></li><li><span><a href="#ndim" data-toc-modified-id="ndim-1.11.2"><span class="toc-item-num">1.11.2&nbsp;&nbsp;</span>ndim</a></span></li><li><span><a href="#size" data-toc-modified-id="size-1.11.3"><span class="toc-item-num">1.11.3&nbsp;&nbsp;</span>size</a></span></li><li><span><a href="#dtype" data-toc-modified-id="dtype-1.11.4"><span class="toc-item-num">1.11.4&nbsp;&nbsp;</span>dtype</a></span></li></ul></li><li><span><a href="#Reshaping" data-toc-modified-id="Reshaping-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>Reshaping</a></span></li><li><span><a href="#Concatenation" data-toc-modified-id="Concatenation-1.13"><span class="toc-item-num">1.13&nbsp;&nbsp;</span>Concatenation</a></span><ul class="toc-item"><li><span><a href="#Size-Mismatch" data-toc-modified-id="Size-Mismatch-1.13.1"><span class="toc-item-num">1.13.1&nbsp;&nbsp;</span>Size Mismatch</a></span></li></ul></li><li><span><a href="#Stack" data-toc-modified-id="Stack-1.14"><span class="toc-item-num">1.14&nbsp;&nbsp;</span>Stack</a></span></li><li><span><a href="#Splitting" data-toc-modified-id="Splitting-1.15"><span class="toc-item-num">1.15&nbsp;&nbsp;</span>Splitting</a></span><ul class="toc-item"><li><span><a href="#vsplit-(vertical)" data-toc-modified-id="vsplit-(vertical)-1.15.1"><span class="toc-item-num">1.15.1&nbsp;&nbsp;</span>vsplit (vertical)</a></span></li><li><span><a href="#hsplit-(horizontal)" data-toc-modified-id="hsplit-(horizontal)-1.15.2"><span class="toc-item-num">1.15.2&nbsp;&nbsp;</span>hsplit (horizontal)</a></span></li></ul></li><li><span><a href="#Sorting" data-toc-modified-id="Sorting-1.16"><span class="toc-item-num">1.16&nbsp;&nbsp;</span>Sorting</a></span><ul class="toc-item"><li><span><a href="#argsort()" data-toc-modified-id="argsort()-1.16.1"><span class="toc-item-num">1.16.1&nbsp;&nbsp;</span>argsort()</a></span></li></ul></li><li><span><a href="#Indexing" data-toc-modified-id="Indexing-1.17"><span class="toc-item-num">1.17&nbsp;&nbsp;</span>Indexing</a></span><ul class="toc-item"><li><span><a href="#Slice-indexing" data-toc-modified-id="Slice-indexing-1.17.1"><span class="toc-item-num">1.17.1&nbsp;&nbsp;</span>Slice indexing</a></span></li><li><span><a href="#Fancy-Indexing" data-toc-modified-id="Fancy-Indexing-1.17.2"><span class="toc-item-num">1.17.2&nbsp;&nbsp;</span>Fancy Indexing</a></span></li></ul></li><li><span><a href="#Subarray" data-toc-modified-id="Subarray-1.18"><span class="toc-item-num">1.18&nbsp;&nbsp;</span>Subarray</a></span><ul class="toc-item"><li><span><a href="#copy()" data-toc-modified-id="copy()-1.18.1"><span class="toc-item-num">1.18.1&nbsp;&nbsp;</span>copy()</a></span></li></ul></li><li><span><a href="#Conditional-Indexin-/-(filter)" data-toc-modified-id="Conditional-Indexin-/-(filter)-1.19"><span class="toc-item-num">1.19&nbsp;&nbsp;</span>Conditional Indexin / (filter)</a></span></li><li><span><a href="#Sum" data-toc-modified-id="Sum-1.20"><span class="toc-item-num">1.20&nbsp;&nbsp;</span>Sum</a></span><ul class="toc-item"><li><span><a href="#Belirli-Axis-uzerinde-toplama" data-toc-modified-id="Belirli-Axis-uzerinde-toplama-1.20.1"><span class="toc-item-num">1.20.1&nbsp;&nbsp;</span>Belirli Axis uzerinde toplama</a></span></li></ul></li><li><span><a href="#Axisler-Hatirlatma" data-toc-modified-id="Axisler-Hatirlatma-1.21"><span class="toc-item-num">1.21&nbsp;&nbsp;</span>Axisler Hatirlatma</a></span></li><li><span><a href="#All" data-toc-modified-id="All-1.22"><span class="toc-item-num">1.22&nbsp;&nbsp;</span>All</a></span></li><li><span><a href="#Any" data-toc-modified-id="Any-1.23"><span class="toc-item-num">1.23&nbsp;&nbsp;</span>Any</a></span></li></ul></li></ul></div>

#  Numpy Array

> Numpy arayler python listelerine benzer.
> Listelerin aksine farkli veri tiplerinde eleman icermezler.


## Listeden Array Yaratmak
__np.array([object],dtype)__

In [1]:
import numpy as np

In [6]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [7]:
type(x)

numpy.ndarray

In [13]:
y= np.array(["a","b",3])
y

array(['a', 'b', '3'], dtype='<U21')

In [14]:
type(y)

numpy.ndarray

In [21]:
z=np.array([3,4,5.7])
z # Integerlar daha genel olan float'a cevirdi

array([3. , 4. , 5.7])

In [20]:
f=np.array([1,2,3.5,41,"22"])
f # Butun integer ve floatlar,  daha genel olan string e cevirildi.

array(['1', '2', '3.5', '41', '22'], dtype='<U32')

## Array Data tipini manuel belirtmek 
__dtype__

In [22]:
x=np.array([1,2,3,4.6],dtype ="int32")
print(x)

[1 2 3 4]


In [23]:
x=np.array([1,2,3,4,5],dtype="str")

In [25]:
print(x)

['1' '2' '3' '4' '5']


In [26]:
x=np.array(["a"],dtype="int32")

ValueError: invalid literal for int() with base 10: 'a'

In [32]:
x=np.array(["4.2"],dtype="int32")

ValueError: invalid literal for int() with base 10: '4.2'

In [27]:
x=np.array(["5"],dtype="int32")

In [29]:
print(x) # Demekki integer gosterimi olmasi gerek!

[5]


## Zero Array
__np.zeros(shape,dtype)__

In [37]:
np.zeros(10) # Default olarak elemanlari float olarak gelir.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [51]:
np.zeros(10,dtype="int32")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [54]:
np.zeros([3,2],dtype="bool")

array([[False, False],
       [False, False],
       [False, False]])

### Multidimensional Zero Array

In [43]:
print(np.zeros((3,4))) # cift parantez onemli!
print("-------------------")
print(np.zeros([3,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
np.zeros([3,5,5]) # bu sefer ilk parametre boyut, 5x5 Lik 3 tane arka arkaya matris dusunebiliriz.

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

## Spesific element array
### np.full()

### HATIRLATMA
__NOTEBOOKDA shift+tab ile nasil paramaetreler aldigini gorebiliriz__

In [66]:
np.full((4,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [69]:
np.full(4,5,5) # HATA !!!

array([5, 5, 5, 5])

In [71]:
np.full(4,5) # O Halde default olarak 4x1 lik array i 5 ile doldurur.

array([5, 5, 5, 5])

In [73]:
np.full([4,2],5.2) # Okey sikinti yok

array([[5.2, 5.2],
       [5.2, 5.2],
       [5.2, 5.2],
       [5.2, 5.2]])

In [74]:
np.full([4,2],5.2 , dtype=str) 

array([['5', '5'],
       ['5', '5'],
       ['5', '5'],
       ['5', '5']], dtype='<U1')

Float bir degeri string almak istersek once integer'a cast ediyor !

In [76]:
np.full([4,2],"5.2")  # Tabiki boyle alabiriz

array([['5.2', '5.2'],
       ['5.2', '5.2'],
       ['5.2', '5.2'],
       ['5.2', '5.2']], dtype='<U3')

## Consequtive Array's
__np.arange(start,stop,step,)__

In [77]:
# [0,12)
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [80]:
x=np.arange(0,12,2)
x


array([ 0,  2,  4,  6,  8, 10])

In [83]:
y=np.arange(12,0,-2)
y

array([12, 10,  8,  6,  4,  2])

## Dividing Interval
__np.linspace(start,stop,num)__  
Default olarak 50 parcaya boler.


In [84]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [87]:
# Kac parcaya bolecegini belirtelim
np.linspace(1,3,num=5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [88]:
np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

Baslagic ve bitis noklari default olarak dahil etmesini istemessek;

In [90]:
np.linspace(1,3,5,endpoint=False)

array([1. , 1.4, 1.8, 2.2, 2.6])

Floatlarda 'da gecerli

In [91]:
np.linspace(1.4,2.7,5)

array([1.4  , 1.725, 2.05 , 2.375, 2.7  ])

## Normal Distribution Array
__np.random.normal(mean,std,size)__


In [93]:
np.random.normal(0,1,(4,5)) # ortalamasi 0 standart sapmasi 1 olan 4e5lik

array([[-2.32176561,  0.43795856, -0.51017011,  1.11062251,  0.63784951],
       [-1.03779294,  1.23508852, -0.05632805, -0.52808345,  0.00851872],
       [-0.33484915, -0.68272274, -0.89617369, -0.11246832,  0.66156393],
       [ 0.70124196, -1.63288093, -0.2226272 ,  0.64084707, -0.35575293]])

In [95]:
np.random.normal(0,100,(4,5)) # standart sapma arttikca meandan uzaklasma artabiliyor.

array([[  13.55364219,  -52.42110028,   66.6678969 , -154.50124088,
        -237.14271001],
       [ -27.615284  ,   28.44225855,  -60.90870243,   58.0350082 ,
          29.24170579],
       [ -74.88811736,  -70.61285034,   56.74621317,  -54.23376927,
          33.33240001],
       [  50.28073254,  -33.96138152, -181.7713398 ,   70.49795935,
          26.90056931]])

In [96]:
np.random.normal(10,1,(4,5))

array([[10.71120624,  9.57954451,  9.6210727 ,  9.79569239,  8.88543506],
       [10.76820714,  9.83637367, 12.3059119 ,  9.24288115, 10.36753168],
       [10.06934138, 10.72118189, 10.66870006,  9.95368911, 11.35441648],
       [ 8.10530484, 11.24892175, 10.43644067,  8.60313262,  9.80229617]])

## Random Integer Array
__np.random.randint(low,high,size)__  
[low,high)

In [98]:
np.random.randint(0,11,(10,2))

array([[ 6,  2],
       [ 7,  2],
       [ 2, 10],
       [10,  8],
       [ 2,  2],
       [ 2,  7],
       [ 5,  9],
       [ 6,  6],
       [ 9,  9],
       [ 3,  3]])

In [99]:
np.random.randint(0,11,(3,5,5))

array([[[ 5,  2, 10,  7,  9],
        [ 7,  6,  7,  6,  5],
        [ 9,  6,  3,  0, 10],
        [ 3,  3,  0, 10,  7],
        [ 2,  0,  9,  4, 10]],

       [[ 0,  7,  6,  5,  8],
        [ 1,  8,  9,  1,  0],
        [ 0,  8,  1,  1,  0],
        [ 4,  2,  4,  1,  5],
        [ 2,  3,  4,  8,  9]],

       [[ 3,  1,  4,  4,  8],
        [ 3,  8,  6,  5,  1],
        [ 4, 10,  6,  0,  0],
        [ 7,  3,  3,  0,  9],
        [ 7,  8,  3,  4,  4]]])

For loopun icerisinde _ underscore'unu  kullanirsak bunu loopda kullanmayacagim anlamina gelir.(ortak dil olarak)

In [105]:
d={}
for _ in range(20000):
    val=np.random.randint(1,11)
    if val not in d:
        d[val]=1
    else:
        d[val]+=1



In [106]:
d

{8: 1993,
 7: 1992,
 1: 2002,
 4: 2000,
 3: 1986,
 9: 2005,
 2: 2005,
 6: 2029,
 5: 2004,
 10: 1984}

## Identity Matrix
__np.eye()__


In [107]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [111]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## Array Operations

In [113]:
a=[2,3,4]
b=[4,5,6]
a*b # Demekki listelerde carpma tanimli degil

TypeError: can't multiply sequence by non-int of type 'list'

- __liste bir integer ile carpilirsa ard arda concatanation yapar__

In [114]:
a=[2,3,4]
a*3

[2, 3, 4, 2, 3, 4, 2, 3, 4]

In [115]:
[2,3,4] + [5,6,7] + [8,9,10]

[2, 3, 4, 5, 6, 7, 8, 9, 10]

- __numpy'da * operatoru iki numpy array arasinda tanimlidir.Element-wise(eleman-bazli) carpim yapar.__

In [116]:
x=np.array([1,2,3])
y=np.array([4,5,6])

x * y

array([ 4, 10, 18])

- __+ operatoru element-wise toplam yapar__

In [117]:
x=np.array([1,2,3])
y=np.array([4,5,6])

x + y

array([5, 7, 9])

In [118]:
x=np.array([1,2,3])

3*x

array([3, 6, 9])

## Array Attributes

### .shape

In [133]:
x=np.zeros([2,3])
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [128]:
y=np.zeros((2,3,4))
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [140]:
x.shape 

(2, 3)

In [141]:
y.shape

(2, 3, 4)

### ndim
__dimensions__


In [142]:
x.ndim # 2 boyutlu

2

In [143]:
y.ndim # 3 boyutlu

3

### size
__Kac elemanli__

In [146]:
x.size

6

In [147]:
y.size

24

###  dtype

In [148]:
x.dtype

dtype('float64')

## Reshaping

In [158]:
x=np.arange(1,11)
print(x)
x.size
x.reshape(5,2)


[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [159]:
x.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [162]:
x.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

__-1 Boyuta karar vermek__

In [165]:
x.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

-1 ile boyutlandirdigimiz zaman x ' in size ini hesapliyor = 10 .   
2 parametresi veriyoruz. Python arka planda su islemi yapiyor 2 * x = 10   
o zaman 5 satir koymaliyim.

In [166]:
x.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

__YENI BOYUT EKLEMEK__

In [176]:
x=np.arange(1,11)
print(x)
x.shape

[ 1  2  3  4  5  6  7  8  9 10]


(10,)

In [169]:
x[np.newaxis,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [171]:
x[np.newaxis,:].shape

(1, 10)

In [172]:
x[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [173]:
x[:,np.newaxis].shape

(10, 1)

## Concatenation

In [178]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

np.concatenate([x,y])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

__liste de concatane edilebilir__


In [179]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
l=[10,11]

np.concatenate([x,y,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 11])

In [180]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
l=[10,11.2]

np.concatenate([x,y,l])



array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. , 10. ,
       11.2])

__Numpy arrayler homojen listeler oldugu icin daha genel olan float'a casting yapti__

---

__! ! ! Liste olmasi gerekmez tuple veri tipinide concatenete() islemine sokabiliriz.! ! !__

In [181]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
l=(10,11.2)

np.concatenate([x,y,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. , 10. ,
       11.2])

###  Size Mismatch

In [195]:

x=np.array([1,2,3,4,5,6])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [194]:
y=np.array([[1,2,3],[4,5,6]])
y


array([[1, 2, 3],
       [4, 5, 6]])

In [196]:
x.size

6

In [197]:
y.size

6

In [202]:
x.shape # Row column mantigi yok!

(6,)

In [201]:
y.shape # Row column mantigi var

(2, 3)

In [205]:
np.concatenate([x,y])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

__axis belirtilmediginde default olarak row olarak eklenir.__

In [219]:
np.concatenate([y,y])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

__axis =1 olarak belirtildiginde yanina column olarak eklenir__

In [235]:
z=np.concatenate([y,y],axis=1) 
z

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [236]:
z.shape

(2, 6)

## Stack
Stack Mantigini Yeni Dimension ekleyip , o dimension uzerinde yaparakta saglayabiliriz.

In [238]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a.shape)
print(b.shape)

(4,)
(4,)


In [246]:
x=np.stack([a,b])
print(x)
print('--------')
print(x.shape)

[[1 2 3 4]
 [5 6 7 8]]
--------
(2, 4)


In [242]:
x.shape

(2, 4)

In [245]:
x=np.stack([a,b],axis=1)
print(x)
print('------------')
print(x.shape)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
------------
(4, 2)


## Splitting

In [285]:
l=[10,20,30,40,50,60,70,80]
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [286]:
np.split(l,[2,6]) 

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

__Yukaridaki kod 2 ve 6'nin arasina birer centik at ve aralari parcala demek__

In [287]:
np.split(l,[3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

In [288]:
np.split(l,[4]) # Tek bir noktada belirlenebilir.

[array([10, 20, 30, 40]), array([50, 60, 70, 80])]

__Python listeleri bolunebildigi gibi , Numpy array'lerde bolunebilir__

In [289]:
a=np.array([1,2,3,4,5,6,7])
np.split(a,[4])

[array([1, 2, 3, 4]), array([5, 6, 7])]

__Multi dimensional arraylerde split__

In [290]:
a=np.array([1,2,3,4,5,6,7,9,10,11]).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  9],
       [10, 11]])

In [291]:
np.split(a,[3]) # 3. satirdan itibaren ayirma yapti dimension'i Bozmadi

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  9],
        [10, 11]])]

__SPLIT ' IN SONUCUNU BIRDEN COK DEGISKENE ESITLEME__

In [292]:
a , b = (1, 10)

In [294]:
a

1

In [295]:
b

10

In [296]:
l=l=[10,20,30,40,50,60,70,80]
x,y,z = np.split(l,[2,6]) 

In [297]:
x

array([10, 20])

In [298]:
y

array([30, 40, 50, 60])

In [299]:
z

array([70, 80])

### vsplit (vertical)

In [320]:
a=np.array([[1,2,3,4,5,6,7,9,10,11]]).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  9, 10, 11]])

In [323]:
x,y = np.vsplit(a,[1])
print(x)
print(y)

[[1 2 3 4 5]]
[[ 6  7  9 10 11]]


### hsplit (horizontal)

In [342]:
a=np.array([1,2,3,4,5,6,7,9,10,11]).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  9, 10, 11]])

In [354]:
np.hsplit(a,[1,3])[0]

array([[1],
       [6]])

In [355]:
np.hsplit(a,[1,3])[1]

array([[2, 3],
       [7, 9]])

In [356]:
np.hsplit(a,[1,3])[2]

array([[ 4,  5],
       [10, 11]])

In [359]:
a=np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [360]:
np.vsplit(a,[2,3]) 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

## Sorting

In [4]:
import numpy as np
a = np.array([30,22,5,41,23,45,87,56])
np.sort(a)

array([ 5, 22, 23, 30, 41, 45, 56, 87])

In [6]:
a # o halde np.sort() a yi guncellemedi

array([30, 22,  5, 41, 23, 45, 87, 56])

In [7]:
a=np.sort(a)

In [9]:
a # Bu sekilde guncelleme yapilabilir.

array([ 5, 22, 23, 30, 41, 45, 56, 87])

In [12]:
a = np.array([30,22,5,41,23,45,87,56])
a.sort()

In [14]:
a # o halde a=np.sort(a)  == a.sort()

array([ 5, 22, 23, 30, 41, 45, 56, 87])

### argsort()

In [15]:
a = np.array([7,1,4,2,3,5,6,9])
np.argsort(a)

array([1, 3, 4, 2, 5, 6, 0, 7])

__siralanmis halinin indexlerini array icerisinde dondurur.__

## Indexing 

In [17]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
a[0],a[1]

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [20]:
a[0,0]

1

In [21]:
a[0][0]

1

In [23]:
a[0].ndim

1

In [24]:
a[1,1]=10

In [26]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [27]:
a[0][2]=23.5
a

array([[ 1,  2, 23,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Slice indexing

In [28]:
a=np.arange(1,21).reshape(4,5)

In [29]:
a[0,3]

4

In [30]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
a[:2] # birsey belli etmessek 0 olarak alir

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [36]:
a[::2] # bastan sonra 2ser atla

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [61]:
a[1::2] # 2 yine step oldu

array([[5, 6, 7, 8]])

In [41]:
a[:,3] # Tum rowlar fakat 3. indexdekileri al

array([ 4,  9, 14, 19])

In [43]:
a[::2,3] # Bastan sona 2 ser atlayarak 3. indexleri al

array([ 4, 14])

In [44]:
a[2,3]

14

In [51]:
a[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [50]:
a[0:2,0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [52]:
a[::,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [53]:
a[::,4:]

array([[ 5],
       [10],
       [15],
       [20]])

ORNEK
```
a=np.arange(1,13).reshape(3,4)
```
```
array([[ 1, 2, 3, 4],[ 9, 10, 11, 12]]) Bunu Dondurmek istiyoruz
```


In [55]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
a[::2]

array([[ 4],
       [12]])

In [59]:
a[::2,2:4]

array([[ 3,  4],
       [11, 12]])

### Fancy Indexing
Simdiye kadar , hep belirli elemanlari , belirli kesitteki elemanlari veya belirli elemanlari atlaya atlaya aldik.Fancy indexing ile birkac tane belirli indexteki elemani bana dondur demis olacagiz. 

In [68]:
x=np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
indx=[0,3,4,5,9]

In [67]:
x[indx]

array([ 1,  4,  5,  6, 10])

In [70]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
a[0:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [83]:
a[0:,1:3].shape

(3, 2)

In [79]:
a[0:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [80]:
a[0:,[1,3]].shape

(3, 2)

In [85]:
a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [89]:
indx1=[1,3,2] # Row
indx2=[3,0,2] # Couloumb
a[indx1,indx2] #1. row 3. columb | 3. row 0. Column | 2.row 2.column - Kesistir demek

array([ 8, 15, 12])

__Fancy indexing sonucunu belirli index'e esitlemek__

In [99]:
a=np.array([1,2,3,4,5,6,7])
indx=[1,3,2]
a[indx]

array([2, 4, 3])

In [102]:
a[indx]=[10,20,30] # 1. INDEXI 10 A 3. INDEXI 20 YE 2. INDEXI 30 A ESITLE

In [103]:
a

array([ 1, 10, 30, 20,  5,  6,  7])

## Subarray

In [104]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [130]:
b=a[:2,:3]

In [131]:
b[0,0]=100

In [140]:
b

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [141]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

__a array'i de guncellendi__  
__bunu engellemek icin;__

### copy()


In [142]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [143]:
b=a[::,:3].copy()

In [144]:
b

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [145]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

##  Conditional Indexin / (filter)

In [150]:
a=np.arange(1,10)

In [151]:
a < 5 # 5 den kucuk degerleri getir.

array([ True,  True,  True,  True, False, False, False, False, False])

In [154]:
a[a<5] # Yukarda true olan degerleri dondur.

array([1, 2, 3, 4])

In [155]:
flt= a < 3

In [156]:
a[flt]

array([1, 2])

In [170]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([2,3,3,4,5,61,7,8,11])
a,b

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 2,  3,  3,  4,  5, 61,  7,  8, 11]))

In [171]:
a.size,b.size

(9, 9)

In [172]:
a == b 

array([False, False,  True,  True,  True, False,  True,  True, False])

In [174]:
a[a==b] # asadaki ile ayni

array([3, 4, 5, 7, 8])

In [176]:
b[a==b] # Ayni indexde ayni deger var ise true

array([3, 4, 5, 7, 8])

__Brodcasting__

In [177]:
a == 1

array([ True, False, False, False, False, False, False, False, False])

In [179]:
a < 3 or a > 5  # Bunu numpy arraylerde kullanamiyoruz.

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [184]:
(a < 3) | (a > 5) # 3 den kucuk veya 5 den buyuk ise True

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [185]:
(a < 3) & (a > 5)

array([False, False, False, False, False, False, False, False, False])

__Multidimensional arraylerde filtreleme__


In [193]:
a=np.arange(0,20).reshape(4,5)

In [195]:
a[a<7]

array([0, 1, 2, 3, 4, 5, 6])

In [196]:
a < 7 

array([[ True,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

__SORU__
```
a=np.arange(-5,3).reshape(2,4)

Aşağıdakilerden hangisi 0’dan küçük veya 2’ye eşit array değerlerini döndürür?
```

In [198]:
a=np.arange(-5,3).reshape(2,4)
a

array([[-5, -4, -3, -2],
       [-1,  0,  1,  2]])

In [201]:
a[(a<0) | (a==2)]

array([-5, -4, -3, -2, -1,  2])

## Sum

In [204]:
a=np.arange(1,21).reshape(4,5)

In [205]:
np.sum(a)

210

In [206]:
filt = a<5

In [207]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [210]:
np.sum(filt) # 4 deger varmis.

4

In [212]:
a[filt] # Dogru bilgi.

array([1, 2, 3, 4])

In [213]:
np.sum(a[filt])

10

In [214]:
flt=(a>5) & (a<9)

In [215]:
a[flt]

array([6, 7, 8])

In [217]:
np.sum(a[flt])

21

### Belirli Axis uzerinde toplama

In [218]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [222]:
np.sum(a,axis=0) # Columnlar toplandi

array([34, 38, 42, 46, 50])

In [223]:
np.sum(a,axis=1) # Satirlar Toplandi

array([15, 40, 65, 90])

##  Axisler Hatirlatma
```
|                 --------> Axis 1 
|
|  Axis 0      
|
v
```

## All
Tum Elemanlar verilen sarti sagliyormu?   

Axislerdede denenebiliyor

In [225]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [226]:
a > -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [227]:
np.all(a>-1)

True

In [229]:
np.all(a>5,axis=1) # 1. satir icin icin false 2. 3. ve 4. dogru

array([False,  True,  True,  True])

## Any

Her hangi bir eleman sagliyor ise True , Yoksa false

yine , Axislerde inceleme yapilabilir.

In [230]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [232]:
a == 2 

array([[False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [233]:
np.any(a==2)

True